apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsappbot-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsappbot-db
  template:
    metadata:
      labels:
        app: whatsappbot-db
    spec:
      containers:
        - name: db
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "AU1Fx^3l**qBh7R"
            - name: POSTGRES_DB
              value: "linqmd"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
