version: '3.8'

services:
  app:
    build: .
    container_name: whatsappbot_app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=linqmd-postgress
      - DB_DATABASE=whatsapptest
      - DB_DIALECT=postgres
      - DB_SSL=true
      - DB_SSL_REJECT_UNAUTHORIZED=false
      - AWS_ACCESS_KEY_ID=your_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
      - AWS_REGION=your_aws_region
      - SQS_INCOMING_QUEUE_URL=https://sqs.your-region.amazonaws.com/your-account-id/incoming_messages
      - SQS_OUTGOING_QUEUE_URL=https://sqs.your-region.amazonaws.com/your-account-id/outgoing_messages
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_started
    networks:
      - whatsappbot_network
    restart: on-failure

  db:
    image: postgres:14
    container_name: whatsappbot_db
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: linqmd-postgress
      POSTGRES_DB: whatsapptest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatsappbot_network

volumes:
  postgres_data:

networks:
  whatsappbot_network:
    driver: bridge