version: '3.8'

services:
  app:
    build: .
    container_name: whatsappbot_app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=linqmd-postgress
      - DB_DATABASE=whatsapp
      - DB_DIALECT=postgres
      - DB_SSL=true
      - DB_SSL_REJECT_UNAUTHORIZED=false
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      - whatsappbot_network
    restart: on-failure

  db:
    image: postgres:14
    container_name: whatsappbot_db
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: linqmd-postgress
      POSTGRES_DB: whatsapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatsappbot_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: whatsappbot_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - whatsappbot_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  whatsappbot_network:
    driver: bridge